# Generated by Django 3.2.3 on 2021-09-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BusBook',
        ),
    ]
