# Generated by Django 3.2.3 on 2021-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('ownername', models.CharField(max_length=50)),
                ('userid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('placeid', models.DecimalField(decimal_places=0, max_digits=2)),
                ('place_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2)),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('google pay', 'google pay')], default='Credit Card', max_length=11)),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='bookingform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem', models.IntegerField()),
                ('date', models.DateField()),
                ('timeslot', models.IntegerField(choices=[('', 'Select'), ('9:00 - 10:00am', '9:00 - 10:00am'), ('10:00 - 11:00am', '10:00 - 11:00am'), ('11:00 - 12:00am', '11:00 - 12:00am'), ('1:00 - 2:00pm', '1:00 - 2:00pm'), ('2:00 - 3:00pm', '2:00 - 3:00pm'), ('3:00 - 4:00pm', '3:00 - 4:00pm')])),
            ],
        ),
        migrations.CreateModel(
            name='tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('', '---Select District---'), ('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], max_length=25)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
